---
AWSTemplateFormatVersion: '2010-09-09'
Description: Synthetic Checks S3 buckets Stack

Mappings: {}

Resources:
  ResultsS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: synthetics-results

  TestsS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: synthetics-tests